### ISSUE TITLE
Layout is undefined

### ISSUE THREAD

**Issue by gedw99** [mariusor/littr.go#1]
I run the main.go..
Server starts up but the Web gui does not work. In the browser i get:
````
html/template: "layout" is undefined
html/template: "layout" is undefined
````

DO i need to embed the assets first ?

**Comment by mariusor** [comment]
Whoa... :) My very first bug ticket for this project.

____

The problem might be if you're trying to run the application from some other working directory than the project root. 

Usually when I test I use something like:

    $ ./run.sh main.go

The `run.sh` script takes care of importing into the running environment the entries from your `.env` file. (Latest commits should have an `.env.example` to get you started)

All these being said, I don't think this project is anywhere close to a state where it can be used by people, please don't get your hopes too much up. :)

And, for closing: thank you for your interest. If you want, you can keep an eye on the bug tracker, as I'm plannign to add a series of milestones and tickets that might shed some light on the status of development and where I want to go next.

**Comment by gedw99** [comment]
Ok I need to use run.sh. my mistake.

Thanks :)

**Comment by gedw99** [comment]
Yes roadmap would be good.
