### ISSUE TITLE
Use sqlx for query generation

### ISSUE THREAD

**Issue by mariusor** [mariusor/littr.go#9]
We currently use hand baked queries for the models package, which look a bit nasty and complicated.

I'm sure we can replace at least some of them with [sqlx](http://jmoiron.github.io/sqlx/) generated ones.

**Comment by gedw99** [comment]
maybe use boltdb with raft ?The current SQL schema is very basic.
also then its very easy to use graphql on top then and do various queries from the front end directly.

If you want some examples let me know.

**Comment by mariusor** [comment]
Thanx, I'll do some research. 

But I don't want to touch the db from the front-end (at least not for now, until I finalize the data structures) as I want flexibility to query every storage back-end (API, db, cache, etc - currently just API, db implemented) in the same way and get the same level of information.

**Comment by gedw99** [comment]
you dont have to touch the db from the front end. It was silly of me to describe it that way. Graphql does not do that, but instead just allows the fronet end to describe the queries.

Anyway, i really think that LiftBridge will accelerate everything for you. Its basically a Acitivty Stream engine. You can still use all the code you ave now on top but it will solve allot of hard problems for you that you will hit.

**Comment by mariusor** [comment]
Thank you again.

I'm not familiar with any of the projects you mentioned and will probably take me a bit of time to actually understand how/where they can help. For now I'm trying to do baby steps in what I hope is a good direction. 

If you can spare the time to show some concrete examples I'm sure it would help a lot, but you've given me some good references, and that's plenty too. :) Cheers.

**Comment by mariusor** [comment]
Moved database interaction to [db](https://github.com/mariusor/littr.go/tree/master/app/db) package and it uses sqlx for item retrieval. It's not fully fleshed yet, but it's workable.
